Use Time instead of DateTime in Revocable concern to play nice with AR
Fixes NoMethodError - undefined method 'getlocal' when calling the
/oauth/token path.

Active record works better with Time, as opposed to DateTime objects,
see issue #668 for more details. Also see
https://gist.github.com/pixeltrix/e2298822dd89d854444b for more about when to use DateTime.